#!/bin/bash
set -eu -o pipefail

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

ROOT="${SELF_DIR}/../.."
INIT="${ROOT}/node/init"
rm -rf "${INIT}"
sha1sum "${ROOT}/package.json" | sed -e 's/^\([^ ]*\) .*$/\1/' > "${INIT}"
