name: Java CI with Maven
"on":
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Checkout alexandria
      uses: actions/checkout@v2
      with:
        repository: alexandria
        path: alexandria
    - name: Build alexandria
      working-directory: ./alexandria
      run: mvn -B install --file pom.xml -P release -Dgpg.skip -DskipTests
    - name: Checkout habitat
      uses: actions/checkout@v2
      with:
        repository: habitat
        path: habitat
    - name: Build habitat
      working-directory: ./habitat
      run: mvn -B install --file pom.xml -P release -Dgpg.skip -DskipTests
    - name: Checkout enigma
      uses: actions/checkout@v2
      with:
        repository: enigma
        path: enigma
    - name: Build enigma
      working-directory: ./enigma
      run: mvn -B install --file pom.xml -P release -Dgpg.skip -DskipTests
    - name: Checkout gearbox
      uses: actions/checkout@v2
      with:
        repository: gearbox
        path: gearbox
    - name: Build gearbox
      working-directory: ./gearbox
      run: mvn -B install --file pom.xml -P release -Dgpg.skip -DskipTests
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: joint
    - name: Build with Maven
      working-directory: ./joint
      run: mvn -B package --file pom.xml -P release -Dgpg.skip
