name: Java CI with Maven
"on":
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Checkout alexandria
      uses: actions/checkout@v2
      with:
        repository: g2forge/alexandria
        path: alexandria
    - name: Build alexandria
      working-directory: ./alexandria
      run: mvn -B install --file pom.xml -P release -Dgpg.skip -DskipTests
    - name: Checkout habitat
      uses: actions/checkout@v2
      with:
        repository: g2forge/habitat
        path: habitat
    - name: Build habitat
      working-directory: ./habitat
      run: mvn -B install --file pom.xml -P release -Dgpg.skip -DskipTests
    - name: Checkout enigma
      uses: actions/checkout@v2
      with:
        repository: g2forge/enigma
        path: enigma
    - name: Build enigma
      working-directory: ./enigma
      run: mvn -B install --file pom.xml -P release -Dgpg.skip -DskipTests
    - name: Checkout gearbox
      uses: actions/checkout@v2
      with:
        repository: g2forge/gearbox
        path: gearbox
    - name: Build gearbox
      working-directory: ./gearbox
      run: mvn -B install --file pom.xml -P release -Dgpg.skip -DskipTests
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: joint
    - name: Build with Maven
      working-directory: ./joint
      run: mvn -B package --file pom.xml -P release,no-test -Dgpg.skip
