name: Java CI with Maven
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
        cache: 'maven'
    - name: Build with Maven
      # Maven deploy on changes (or manual run) to main, otherwise just package it
      run: mvn -B ${{ (((github.event_name == 'push') || (github.event_name == 'workflow_dispatch')) && (github.ref == 'refs/heads/main')) && 'deploy' || 'package' }} --file pom.xml -Prelease,release-snapshot
      env:
        GITHUB_TOKEN: ${{ github.token }}
